# Generated by Django 3.0.3 on 2020-02-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.SmallIntegerField()),
                ('lon', models.SmallIntegerField()),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('data', models.BinaryField()),
            ],
            options={
                'unique_together': {('lat', 'lon')},
                'index_together': {('lat', 'lon')},
            },
        ),
    ]
